# Path to where the unpreprocessed datasets are stored
raw_datasets: write/path/here/
# Derived raw dataset paths
tc_primed: ${.raw_datasets}/tc_primed
sar_cyclobs: ${.raw_datasets}/sar_cyclobs
era5_weatherbench: ${.raw_datasets}/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr
# Path to where the preprocessed dataset will be saved
preprocessed_dataset: 
# Lightning checkpoints directory
checkpoints: 
# Weights and Biases logs directory
wandb_logs: 
# Validation figures directory
validation: 
# Directory for the predictions (arrays)
predictions: 
# Directory for the results (figures, tables, etc.)
results: 

