# Path to where the unpreprocessed datasets are stored
raw_datasets: ${oc.env:SCRATCH}/data/motif/raw/
# Derived raw dataset paths
tc_primed: ${.raw_datasets}/tc_primed
sar_cyclobs: ${.raw_datasets}/sar_cyclobs
era5_weatherbench: ${.raw_datasets}/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr
# Path to where the preprocessed dataset will be saved
preprocessed_dataset: ${oc.env:SCRATCH}/data/motif/preprocessed_pmw_concat_regular/
# Checkpoints directory
checkpoints: ${oc.env:SCRATCH}/checkpoints/

wandb_logs: ${oc.env:SCRATCH}
validation: ${oc.env:SCRATCH}/data/motif/validation
predictions: ${oc.env:SCRATCH}/data/motif/predictions
results: ${oc.env:SCRATCH}/data/motif/results

gpm_tle_dir: ${.raw_datasets}/gpm/tle
gpm_coincidences_dir: ${oc.env:SCRATCH}/data/motif/processed/gpm/coincidences
gpm_pmw_download_dir: ${oc.env:SCRATCH}/data/motif/processed/gpm/pmw_data
gpm_granules_dir: ${oc.env:SCRATCH}/data/motif/processed/gpm/granules

